custom_package = PackageType.create!(title: "Custom",
                                 subtitle: "Create A Custom Package!",
                                 description: "Create your own combination of photo and video shoots",
                                 description_image: "www.nomcre.com/excitement_description image",
                                 show_in_menu: false,
                                 menu_link_text: 'Custom Packages!',
                                 minimum_images: 0,
                                 minimum_videos: 0,
                                 max_models: 2,
                                 base_price: 1,
                                 order: 9,
                                 show_on_index: true,
                                 call_to_action_text: "Create your Custom Package Now!",
                                 header_image: HeaderImage.first)
