HeadlineAdlib.create(title: "How to #great_result in #timeframe Without #thing_you_hate", stage: 'TOFU')
HeadlineAdlib.create(title: "#number Quick Tips to #great_result", stage: 'TOFU')
HeadlineAdlib.create(title: "Why I Don’t #everyone_action ", stage: 'TOFU')
HeadlineAdlib.create(title: "#percentage % of You Will Ignore This in 2020 - #audience_search_topic", stage: 'TOFU')
HeadlineAdlib.create(title: "Why #group_of_people #terrible_result ", stage: 'TOFU')
HeadlineAdlib.create(title: "How to #great_result", stage: 'TOFU')
HeadlineAdlib.create(title: "The #number Lessons #group_of_people Learn in #strategy_name Too Late ", stage: 'TOFU')
HeadlineAdlib.create(title: "The Ultimate Advice For Every #demographic", stage: 'TOFU')
HeadlineAdlib.create(title: "WHAT TO DO AFTER #bl_phase ", stage: 'TOFU')
HeadlineAdlib.create(title: "Why #unconventional_action is Good For #great_result", stage: 'TOFU')
HeadlineAdlib.create(title: "The Fastest Way to Avoid #terrible_result", stage: 'TOFU')
HeadlineAdlib.create(title: "How Smart #group_of_people Solve #common_objection", stage: 'TOFU')
HeadlineAdlib.create(title: "They Say #strategy_name Is Expensive? ", stage: 'TOFU')
HeadlineAdlib.create(title: "What if #strategy_name Doesn’t Work?", stage: 'TOFU')
HeadlineAdlib.create(title: "#strategy_name For #personality_type ", stage: 'TOFU')
HeadlineAdlib.create(title: "#great_result - Testimonial", stage: 'TOFU')
HeadlineAdlib.create(title: "#number Types of #group_of_people & How to #great_result", stage: 'TOFU')
HeadlineAdlib.create(title: "The #number Most Powerful Words You Can Use When #unconventional_action", stage: 'TOFU')
HeadlineAdlib.create(title: "#number Tricks to Avoid #terrible_result", stage: 'TOFU')


HeadlineAdlib.create(title:"Is #everyone_action a Waste of Time?", stage: 'TOFU')
HeadlineAdlib.create(title:"The Single Biggest Reason Why You Will #terrible_result", stage: 'TOFU')
HeadlineAdlib.create(title:"The #number Biggest Lies of #strategy_name", stage: 'TOFU')
HeadlineAdlib.create(title:"The #number Biggest Lies of #thing_you_hate", stage: 'TOFU')
HeadlineAdlib.create(title:"#number Things That Will Hold You Back From #great_result", stage: 'TOFU')
HeadlineAdlib.create(title:"How to Handle #terrible_result", stage: 'TOFU')
HeadlineAdlib.create(title:"#number Tips for all #group_of_people #personality_type", stage: 'TOFU')
HeadlineAdlib.create(title:"My Best Advice on How to #great_result", stage: 'TOFU')
HeadlineAdlib.create(title:"How I went From #terrible_result to #great_result", stage: 'TOFU')
HeadlineAdlib.create(title:"How to Adapt to Changes on #strategy_name", stage: 'TOFU')
HeadlineAdlib.create(title:"Problems With #strategy_name Around The World ", stage: 'TOFU')
HeadlineAdlib.create(title:"The #number Traits That Make You #great_result", stage: 'TOFU')
HeadlineAdlib.create(title:"Will #audience_search_topic Make You Happy?  ", stage: 'TOFU')
HeadlineAdlib.create(title:"Could #unconventional_action Be The Best Thing You Have Ever Done? ", stage: 'TOFU')
HeadlineAdlib.create(title:"How to #unconventional_action So That You #great_result", stage: 'TOFU')
HeadlineAdlib.create(title:"Why You Should Never Do #thing_you_hate", stage: 'TOFU')
HeadlineAdlib.create(title:"The First #number Hours – How to overcome #common_objection", stage: 'TOFU')
HeadlineAdlib.create(title:"The Most Important Lesson From #unconventional_action", stage: 'TOFU')
HeadlineAdlib.create(title:"Why #everyone_action is Actually Bad For You ", stage: 'TOFU')
HeadlineAdlib.create(title:"How #group_of_people 3x Their Success By Using This Trick ", stage: 'TOFU')
HeadlineAdlib.create(title:"#number Techniques To Break Into the 1 percent of #group_of_people", stage: 'TOFU')
HeadlineAdlib.create(title:"The Surprising Secret to Avoiding #thing_you_hate", stage: 'TOFU')
HeadlineAdlib.create(title:"Why #group_of_people Believe They Shouldnt #unconventional_action", stage: 'TOFU')
HeadlineAdlib.create(title:"Is #everyone_action A Thing of The Past? ", stage: 'TOFU')
HeadlineAdlib.create(title:"How I #great_result – Without #everyone_action", stage: 'TOFU')
HeadlineAdlib.create(title:"If You Want to #great_result, Be Obsessed ", stage: 'TOFU')
HeadlineAdlib.create(title:"What Do Top #group_of_people Do Differently? ", stage: 'TOFU')
HeadlineAdlib.create(title:"HOW TO STOP #everyone_action", stage: 'TOFU')
HeadlineAdlib.create(title:"Why #unconventional_action Will Change Everything", stage: 'TOFU')
HeadlineAdlib.create(title:"Stop Searching For #great_result, Start Taking Action! ", stage: 'TOFU')
HeadlineAdlib.create(title:"The Advice Top #group_of_people Won’t Give You ", stage: 'TOFU')
HeadlineAdlib.create(title:"#unconventional_action Tutorial For Beginners 2020 – How to Create #great_result ", stage: 'TOFU')


HeadlineAdlib.create(title:"Stop Caring About #everyone_action", stage: 'TOFU')
HeadlineAdlib.create(title:"#number Smart Strategies to #great_result", stage: 'TOFU')
HeadlineAdlib.create(title:"Uncomfortable Truths About #audience_search_topic", stage: 'TOFU')
HeadlineAdlib.create(title:"Watch Me #unconventional_action in #timeframe", stage: 'TOFU')
HeadlineAdlib.create(title:"Do You #audience_search_topic? – Watch this Now ", stage: 'TOFU')
HeadlineAdlib.create(title:"Should You #audience_search_topic? ", stage: 'TOFU')
HeadlineAdlib.create(title:"The Best Advice For #group_of_people", stage: 'TOFU')
HeadlineAdlib.create(title:"#number Steps to #everyone_action The New Way - 2020", stage: 'TOFU')
HeadlineAdlib.create(title:"Why #thing_you_hate Is Actually Good For you ", stage: 'TOFU')
HeadlineAdlib.create(title:"Why Do So Many #group_of_people Win in #everyone_action ", stage: 'TOFU')
HeadlineAdlib.create(title:"Are Great #group_of_people Made or Born? ", stage: 'TOFU')
HeadlineAdlib.create(title:"This is The Only Way to #great_result in #timeframe", stage: 'TOFU')
HeadlineAdlib.create(title:"Top #number #audience_search_topic's Mistake That #group_of_people Make  ", stage: 'TOFU')
HeadlineAdlib.create(title:"The Single Biggest Reason Why #group_of_people Succeed in #strategy_name ", stage: 'TOFU')
HeadlineAdlib.create(title:"Daily To-Do List For #unconventional_action", stage: 'TOFU')
HeadlineAdlib.create(title:"How to Plan The Ultimate #audience_search_topic Action Plan", stage: 'TOFU')
HeadlineAdlib.create(title:"#number Things That #group_of_people Shouldn’t Do ", stage: 'TOFU')
HeadlineAdlib.create(title:"#number Tips on How to Survive #terrible_result", stage: 'TOFU')
HeadlineAdlib.create(title:"If You #common_objection You Can Still #great_result", stage: 'TOFU')
HeadlineAdlib.create(title:"Do You Recognize the #number Early Warning Signs of #terrible_result?", stage: 'TOFU')
HeadlineAdlib.create(title:"Do You Make These Mistakes in #audience_search_topic?", stage: 'TOFU')
HeadlineAdlib.create(title:"The Lazy #demographic Way to #unconventional_action", stage: 'TOFU')
